### ISSUE TITLE
命名空间问题

### ISSUE THREAD

**Issue by DawsenSu** [DawsenSu/PDWIT_ShipLock#3]
- ## lib命名空间问题

![image](https://user-images.githubusercontent.com/13221292/77214074-31783400-6b48-11ea-8506-201a41c5153b.png)
建议将以上几类命名空间统一为PDIWT_LIB，其余类改为包含静态函数的类。

**Comment by afas2005** [comment]
already changed.

**Comment by DawsenSu** [comment]
在lib_components里的命名空间好想忘改了，下次pull request的时候一起改一下吧。
![image](https://user-images.githubusercontent.com/13221292/77276931-c7ea5800-6cf6-11ea-9ee2-75b6665deb52.png)
@afas2005

**Comment by afas2005** [comment]
lib_components 中建议保留现状吧，如果类中包含的是静态函数，用类来作为命名空间是没问题的，但是如果使用静态类包含其他类做为命名空间，则可能会产生编译问题，而且使用上会不方便，比如嵌套类定义静态变量或命名空间内全局变量等操作。

**Comment by DawsenSu** [comment]
> 但是如果使用静态类包含其他类做为命名空间

这个是什么意思？没有看懂能解释一下吗？

**Comment by DawsenSu** [comment]
保持PDIWT_LIB_SHIPLOCK_Components的命名空间吧
